version: '3.1'

services:

    kibana:
        image: kibana:4.6.4
        ports:
            - 5601:5601

    elasticsearch:
        image: elasticsearch:2.4.0
        ports: 
            - 9200:9200